### ISSUE TITLE
Need contributions

### ISSUE THREAD

**Issue by yogeshhk** [yogeshhk/Awesome-AI-By-Bharat#1]
https://ai4bharat.iitm.ac.in/datasets to be added to Datasets table
https://ai4bharat.iitm.ac.in/models to be added to Models table
https://ai4bharat.iitm.ac.in/tools to the Tools list
https://ai4bharat.iitm.ac.in/publications to the Publications list

**Comment by tanmay-sketch** [comment]
I'm willing to contribute. All the datasets, models, tools, publications mentioned in the website have to be added in the README?

**Comment by yogeshhk** [comment]
> I'm willing to contribute. All the datasets, models, tools, publications mentioned in the website have to be added in the README?

Yes, I think that should be fine.

**Comment by yogeshhk** [comment]
@tanmay-sketch I am planning to move the README.md to my github repo Sarvadnya..., as this repo was not told not to be inline with other AWESOME repos.. I will maintain that file.. hope thats ok
